title: 50 Senz of Sith
author: SithSenz

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


# remote_theme: poole/hyde


# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
